language: csharp
dist: xenial
dotnet: none
git:
  depth: false
env:
  - DOCFX_TOOL="mono docfx.console/tools/docfx.exe"
install:
  - nuget install docfx.console -Version 2.44.0 -ExcludeVersion
script:
  - $DOCFX_TOOL metadata Documentation/docfx.json
  - $DOCFX_TOOL build    Documentation/docfx.json
  - mv _site/toc.html _site/index.html
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local-dir: _site
  on:
    branch: ShipTiles