language: csharp
dist: xenial
dotnet: none
git:
  depth: false
env:
  - DOCFX_TOOL="mono docfx.console/tools/docfx.exe"
install:
  - nuget install docfx.console -Version 2.44.0 -ExcludeVersion
script:
  - $DOCFX_TOOL metadata docfx.json
  - $DOCFX_TOOL build docfx.json
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: ShipTiles