language: cpp
compiler: gcc

os: linux
addons:
  apt:
    packages:
      - g++-7
    sources:
      - ubuntu-toolchain-r-test

install:
  - sudo apt-get install libsfml-dev

script:
  - mkdir build
  - cd build
  - export CC=gcc-7
  - export CXX=g++-7
  - cmake .. -DCMAKE_BUILD_TYPE=Debug
  - cmake --build . --target SFMLTest